version: '3.8'
services:
    client:
      build:
        context: ./client
      ports:
          - 4200:4200
      container_name: client
      depends_on: 
          [api, webapi]
    
    api:
      build: 
        context: ./nodeapi 
      ports:
          - 5000:5000
      container_name: api 
      depends_on: 
          [emongo]
    
    webapi:
      build: 
        context: ./javaapi 
      restart: always 
      ports:
          - 9000:9000
      container_name: webapi 
      depends_on: 
          [emartdb]

    nginx:
      restart: always 
      image: ngnix:latest 
      volume:
       - "./nginx/default.conf:/etc/mginx/conf.d/default.conf"
      ports:
          - 80:80 
      container_name: nginx
      command: ['nginx-debug', '-g', 'daemon off']
      depends_on: 
          [client]
    
    emongo:
      image: mongo:4
      environment:
          - MONGO_INITDB_DATABASE=epoc 
      ports:
          - 27017:27017

    emartdb:
      image: mysql:5.7
      ports:
          - 3306:3306 
      container_name: emartdb 
      environment:
          - MYSQL_ROOT_PASSWORD=emartdbpass
          - MYSQL_DATABASE=books 
    